apiVersion: batch/v1
kind: Job
metadata:
  name: remove-all-default-vpcs
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 432000
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec: 
      serviceAccountName: remove-default-vpc
      containers:
      - name: default-vpc-remover
        image: '<YOUR-DOCKER-REPO>/remove-default-vpc:latest'
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
      restartPolicy: Never
